swecc-uw/swecc-website

- package.json
Removed build stage from GH Action
> Maybe this will deploy!

- .idea/.gitignore
- .idea/modules.xml
- .idea/swecc-website.iml
- .idea/vcs.xml
Author: <name>
Testing forking and adding a contributors txt
> added contributors txt

- contributors.txt
Author: Sunny
Added my name to the contributors text file.
I did this for the demo
> added my name

- contributors.txt
Author: Anthony Wen
Added my name to the contributor.txt
demo
> added my name to contributor

- contributors.txt
Author: Devina
Added myself to contributors
Just updating thingsss
> adding to contributors

- contributors.txt
Author:  Rina Reimer
Added to the contributors.txt
> SWECC Labs: New Contributor

- contributors.txt
Author: Nathan Bekele
contributer name added
Because I will be adding more to this project
> first commit

- contributors.txt
Author: Tim (Randomhash)
update 'contributors.txt' with personal name
instructor told so
not applicable, not ui
> chore: update 'contributors.txt' with personal name

- contributors.txt
> added my name :)

- contributors.txt
Author: <name>
I added my name to contributors.txt.
> I added my name

- contributors.txt
Author: Cleo
Added my name to the contributors file.
Because it is part of the tutorial/
w” comparison would be great!
> added name to contributors

- contributors.txt
Author: Max Lan
I added my name to the contributor's text file
> added my name to contributors.txt

- contributors.txt
Author: Elijah Melton
I added my name to contributers.txt
For the demo
> added my name to the contributers file

- contributors.txt
Author: <name>
I just added my name.
> added my name to contributers!

- contributors.txt
Author: Hitender Oswal
I added my name to the contributor.txt file.
I plan to contribute to this project.
> Added my name to contributors.txt file

- contributors.txt
Author: Jack Scott
Added name to contributers.txt
SWECC Labs demo
> added my name to contributers file

- src/Data/pastOfficers.json
- src/Data/teamMembers.json
Author: Rina Reimer
Changed all officers' names from first names to both first and last
Consistency
> FIX: ensure that all officers' names are their full names

- src/Components/About.js
Author: Annie Cao
I updated the page header and description in the Board Members page.
Keeping a webpage up to date is important, so readers can find the right information.
After:
> Fix bug in Board Members Page

- src/Components/Home.js
> changed date and location for meetings

- src/CSS/Footer.css
- src/Components/Footer.js
- src/Components/FooterMobile.js
Author: <name>
Updated footer to reflect the name change from "Dubvelopers" to "Web Impact"
Added link to Web Impact site in footer
It's a fix to an out-of-date reference to Dubvelopers. Also allows users to navigate to the Web Impact website from the footer.
> Changed collab line in footer to reflect the new name + link

- src/Components/App.js
- src/Components/Footer.js
- src/Components/Home.js
- src/Components/Redirect.js
Author: Shawn
Adds a discord redirect so we can give people the url http://swecc.org/discord
Also removed a console.log in home.js that someone left.
It's nice to be able to share the discord link that way instead of the messy link.
> Add discord redirect and remove console.log

- .github/workflows/management-bots.yaml
> Fix action

- src/CSS/Navbar.css
- src/Components/Navbar.js
Added a pulse effect when clicking the logo button
Author: Sean Benoit
There's now a simple pulse animation when the SWECC logo is clicked, it grows bigger and then shrinks for about half a second
This change makes the website feel a little bit more dynamic. It's also not too out of control out of consideration for people who can be sensitive to certain effects.
https://github.com/user-attachments/assets/e0d249f5-6884-48e2-8f8c-1463d61d58ce
> Added animation to logo

- src/CSS/OfficerApplication.css
- src/CSS/Officers.css
- src/Components/App.js
- src/Components/OfficerApplication.js
- src/Components/Officers.js
- src/Components/Utils/Utils.js
Author: Mark Han
Added an officer application page and linked it in the officers page.
The new officer applications are opening up soon.
> Markhan0805 47 create officer application page
